### ISSUE TITLE
SQL DB List Insertion not working

### ISSUE THREAD

**Issue by Luminarys** [install-logos/riceDB#24]
The current way the image list is inserted, the DB registers the image as:
"images": "['http://bwasti.com:9001/test.jpg']",
rather than "images:["http://bwasti.com:9001/test.jpg"]

**Comment by potsmodern** [comment]
DB saves the images as a JSON array.

**Comment by Luminarys** [comment]
but they're being pulled out as strings is the issue. Those quotes are screwing this up. I've applied a temporary fix by just using a single photo and not doing the array calls which has gotten everything working but if we want multiple images this is an issue.

**Comment by potsmodern** [comment]
`exec query`

**Comment by potsmodern** [comment]
I don't know what the problem is. Can you paste the Traceback and error?
