### ISSUE TITLE
Better logo?

### ISSUE THREAD

**Issue by Yottawatts** [install-logos/ricedb#27]
The current one looks like shit
![ricedb-black](https://cloud.githubusercontent.com/assets/5554865/6818682/9706ae8e-d271-11e4-9116-f626d3337d31.png)
![ricedb-white](https://cloud.githubusercontent.com/assets/5554865/6818683/98c05d74-d271-11e4-851f-7006bc5337e9.png)

I made two versions for you in GIMP; the image in the background is public domain, and the font is San Francisco Display from Apple. If you need these to be re-rendered, here's the [xcf file](http://a.pomf.fi/ngscob.xcf)

**Comment by Luminarys** [comment]
Feel free to edit the readme.md and use one of these. If it looks good I'll merge it.

**Comment by nih0** [comment]
@Yottawatts Create a pr with the white version, i'll merge it then.

**Comment by Yottawatts** [comment]
Pull request is done, feel free to take a look; I also took the liberty of adding a slightly different tagline.
https://github.com/install-logos/riceDB/pull/28

**Comment by potsmodern** [comment]
@RicebowlLinux took issue with the logo for being too similar to theirs. Guess we have to change it....... again.

**Comment by emgram769** [comment]
why? the logo itself is for an entirely different product (a configuration management system not a distro), the use of chopsticks+bowl is not unique, our use of the chopsticks + bowl looks like "db" whereas theres seems random.

do they have a trademark or any other reason to steam the pot?

**Comment by Yottawatts** [comment]
![ricedb-black](https://cloud.githubusercontent.com/assets/5554865/6860320/e72f21d4-d3e3-11e4-9c9f-ed15f714905d.png)
![ricedb-white](https://cloud.githubusercontent.com/assets/5554865/6860325/ee8f0e12-d3e3-11e4-926e-ecd0f5a54c04.png)
Again, I have a finalized version of my logo. @emgram769 I know you took issue with the "yellow texture in the background", which is actually a rice terrace:
![rice-terraces-214725](https://cloud.githubusercontent.com/assets/5554865/6860344/16b08060-d3e4-11e4-9312-7349ae6a0e06.jpg)
I'll see if I can find something else I can use, but as of right now, I think this is the best logo for the moment.
